"""
Tests for PDF export functionality.

Unit tests for core/pdf_export.py
"""
import pytest
from core.pdf_export import export_mom_pdf


class TestPDFExport:
    """Test suite for PDF export functionality."""
    
    def test_export_mom_pdf_returns_bytes(self):
        """PDF export should return bytes."""
        title = "Test Meeting"
        mom_text = "Meeting Objective:\nNone\n\nDecisions:\n1. Made a decision"
        
        result = export_mom_pdf(title, mom_text)
        
        assert isinstance(result, bytes), "export_mom_pdf should return bytes"
    
    def test_export_mom_pdf_bytes_not_empty(self):
        """PDF bytes should not be empty."""
        title = "Test Meeting"
        mom_text = "Meeting Objective:\nNone\n\nDecisions:\n1. Made a decision"
        
        result = export_mom_pdf(title, mom_text)
        
        assert len(result) > 0, "PDF bytes should not be empty"
    
    def test_export_mom_pdf_contains_pdf_header(self):
        """PDF should contain PDF file signature."""
        title = "Test Meeting"
        mom_text = "Meeting Objective:\nNone"
        
        result = export_mom_pdf(title, mom_text)
        
        # PDF files start with %PDF
        assert result.startswith(b'%PDF'), "Generated bytes should be valid PDF (start with %PDF)"
    
    def test_export_mom_pdf_preserves_full_text(self):
        """PDF content should preserve full MOM text without truncation."""
        title = "Test Meeting"
        # Use a moderately long MOM text with full action items
        mom_text = """Meeting Objective:
To discuss project status and roadmap

Attendees:
- Alice Johnson
- Bob Smith
- Carol White

Decisions:
1. Approved budget allocation for Q2
2. Agreed on product launch date: March 15, 2026

Action Items:
1. Prepare detailed project report - Alice Johnson - Due: 2026-02-25
2. Schedule stakeholder meeting - Bob Smith - Due: 2026-02-20
3. Update technical specifications - Carol White - Due: 2026-03-01

Parking Lot:
- Future API redesign
- Infrastructure cost reduction

Notes:
This was a productive meeting with clear outcomes."""
        
        result = export_mom_pdf(title, mom_text)
        
        # Check that result is valid bytes
        assert isinstance(result, bytes) and len(result) > 0, "PDF should generate valid bytes"
        # Verify it's a PDF
        assert result.startswith(b'%PDF'), "Should be valid PDF"
        # Note: Can't easily extract and verify full text from PDF without parsing,
        # but we ensure it's generated without errors, which means content was preserved
    
    def test_export_mom_pdf_with_long_action_items(self):
        """PDF should handle long action items without truncation."""
        title = "Status Review Meeting"
        mom_text = """Action Items:
1. Complete comprehensive analysis of market trends and competitive landscape including pricing strategies and feature comparisons across all major competitors in the industry - John Doe - Due: 2026-03-15
2. Prepare detailed implementation roadmap with resource allocation, timeline, and risk mitigation strategies for the new platform infrastructure upgrade - Jane Smith - Due: 2026-03-10
3. Conduct stakeholder interviews to gather requirements and validate assumptions about system performance and scalability needs - Mike Johnson - Due: 2026-02-28"""
        
        result = export_mom_pdf(title, mom_text)
        
        # Verify PDF was generated successfully
        assert isinstance(result, bytes), "Should return bytes"
        assert len(result) > 0, "PDF should not be empty"
        assert result.startswith(b'%PDF'), "Should be valid PDF"
    
    def test_export_mom_pdf_with_special_characters(self):
        """PDF should handle special characters correctly."""
        title = "Meeting & Discussion"
        mom_text = """Decisions:
1. Approve budget <$10k> for Q1 & Q2
2. Support "new initiative" with 50% resources
3. Timeline: 2026-01-01 to 2026-12-31"""
        
        result = export_mom_pdf(title, mom_text)
        
        assert isinstance(result, bytes), "Should return bytes"
        assert len(result) > 0, "PDF should not be empty"
        assert result.startswith(b'%PDF'), "Should be valid PDF"
    
    def test_export_mom_pdf_raises_on_empty_text(self):
        """export_mom_pdf should raise ValueError for empty mom_text."""
        title = "Empty Meeting"
        
        with pytest.raises(ValueError, match="MOM text cannot be empty"):
            export_mom_pdf(title, "")
    
    def test_export_mom_pdf_raises_on_whitespace_only(self):
        """export_mom_pdf should raise ValueError for whitespace-only text."""
        title = "Whitespace Meeting"
        
        with pytest.raises(ValueError, match="MOM text cannot be empty"):
            export_mom_pdf(title, "   \n  \t  ")
    
    def test_export_mom_pdf_with_multiple_pages(self):
        """PDF should handle content that spans multiple pages."""
        title = "Comprehensive Meeting Minutes"
        # Generate text that should span multiple pages
        mom_text = "Meeting Objective: Extended discussion\n\n"
        mom_text += "Attendees (20 people):\n"
        for i in range(1, 21):
            mom_text += f"- Attendee {i}\n"
        
        mom_text += "\nDecisions (15 items):\n"
        for i in range(1, 16):
            mom_text += f"{i}. Decision {i}: This is a detailed decision statement with comprehensive explanation\n"
        
        mom_text += "\nAction Items (20 items):\n"
        for i in range(1, 21):
            mom_text += f"{i}. Action {i}: Comprehensive action item with detailed description and multiple steps - Owner {i} - Due: 2026-03-{(i%28)+1:02d}\n"
        
        result = export_mom_pdf(title, mom_text)
        
        # If this doesn't raise an exception and generates valid PDF, it handles multi-page
        assert isinstance(result, bytes), "Should return bytes"
        assert len(result) > 0, "PDF should not be empty"
        assert result.startswith(b'%PDF'), "Should be valid PDF"
        # PDF with multiple pages should be larger than minimal PDF but exact size varies due to compression
        assert len(result) > 2000, "Multi-page PDF should be reasonably sized"
    
    def test_export_mom_pdf_title_included(self):
        """PDF should include the title in the document."""
        title = "UniqueTestTitle2026"
        mom_text = "Content for test"
        
        result = export_mom_pdf(title, mom_text)
        
        # Verify PDF was generated
        assert isinstance(result, bytes), "Should return bytes"
        assert len(result) > 0, "PDF should not be empty"
        assert result.startswith(b'%PDF'), "Should be valid PDF"
        # Title is typically encoded in PDF stream
        # We verify generation succeeds which means title was processed


class TestPDFExportIntegration:
    """Integration tests for PDF export with realistic MOM data."""
    
    def test_export_complete_mom_workflow(self):
        """Test exporting a complete MOM through the typical workflow."""
        title = "Q1 Strategy Review Meeting"
        mom_text = """Meeting Objective:
Review Q1 performance and plan Q2 strategy

Attendees:
- Executive Director
- Product Manager
- Engineering Lead
- Business Analyst

Decisions:
1. Approved budget increase for hiring
2. Approved new product feature roadmap
3. Approved marketing campaign budget

Action Items:
1. Draft job descriptions for 3 open positions - Executive Director - Due: 2026-02-24
2. Finalize Q2 feature specifications - Product Manager - Due: 2026-02-23
3. Estimate engineering effort for new features - Engineering Lead - Due: 2026-02-25

Next Meeting:
March 1, 2026 at 2:00 PM

Status: Complete"""
        
        result = export_mom_pdf(title, mom_text)
        
        # Comprehensive validation
        assert isinstance(result, bytes), "Should return bytes"
        assert len(result) > 0, "PDF should not be empty"
        assert result.startswith(b'%PDF'), "Should be valid PDF"
        assert len(result) > 1000, "Complete MOM should generate reasonable PDF size"
    
    def test_export_mom_with_confidential_markers(self):
        """Test exporting MOM with confidential information markers."""
        title = "Confidential Financial Review"
        mom_text = """Meeting Objective:
Confidential budget review and salary discussions

Sensitive Items:
- SALARY: Discussed compensation adjustments (confidential)
- NRIC validation for new employee onboarding
- Bank account setup for vendor payments

Decisions:
1. Approved compensation adjustments (Confidential)
2. Approved vendor payment terms"""
        
        result = export_mom_pdf(title, mom_text)
        
        assert isinstance(result, bytes), "Should handle content with confidential markers"
        assert len(result) > 0, "PDF should not be empty"
        assert result.startswith(b'%PDF'), "Should be valid PDF"
