"""
PDF export for MOM documents.

Provides simple export_mom_pdf function to generate PDF bytes from MOM text.
"""
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.colors import HexColor


def export_mom_pdf(title: str, mom_text: str) -> bytes:
    """
    Export MOM text to PDF bytes.
    
    Renders monospaced text with automatic line wrapping and page breaks.
    
    Args:
        title: PDF title/header (meeting name)
        mom_text: Formatted MOM text content
        
    Returns:
        PDF content as bytes
        
    Raises:
        ValueError: If mom_text is empty
    """
    if not mom_text or not mom_text.strip():
        raise ValueError("MOM text cannot be empty")
    
    # Create BytesIO buffer
    buffer = BytesIO()
    
    # Create PDF document with standard margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.5 * inch,
        leftMargin=0.5 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.5 * inch,
    )
    
    # Create custom styles
    styles = _create_styles()
    
    # Build story (content)
    story = []
    
    # Add header with title and date
    story.append(Paragraph(f"<b>{_escape_html(title)}</b>", styles['header_title']))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['header_date']))
    story.append(Spacer(1, 0.2 * inch))
    
    # Add MOM content using monospaced preformatted text
    # Preformatted preserves spacing and line breaks while allowing automatic wrapping
    story.append(Preformatted(mom_text, styles['monospace_body']))
    
    # Add footer
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph(
        "<i>This document was automatically generated by ClearMeet</i>",
        styles['footer']
    ))
    
    # Build PDF
    doc.build(story)
    
    # Get bytes
    buffer.seek(0)
    return buffer.getvalue()


def _create_styles() -> dict:
    """
    Create custom paragraph and preformatted styles.
    
    Returns:
        Dictionary of style objects
    """
    base_styles = getSampleStyleSheet()
    
    # Header title style
    header_title = ParagraphStyle(
        'HeaderTitle',
        parent=base_styles['Heading1'],
        fontSize=16,
        textColor=HexColor('#1a1a1a'),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    # Header date style
    header_date = ParagraphStyle(
        'HeaderDate',
        parent=base_styles['Normal'],
        fontSize=10,
        textColor=HexColor('#666666'),
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    # Monospaced body for preserving MOM formatting
    monospace_body = ParagraphStyle(
        'MonospaceBody',
        parent=base_styles['Normal'],
        fontSize=9,
        textColor=HexColor('#2c3e50'),
        spaceAfter=0,
        alignment=TA_LEFT,
        fontName='Courier',
        leading=12,  # Line height for better readability
        wordWrap='LB'  # Word wrap at character boundaries
    )
    
    # Footer style
    footer = ParagraphStyle(
        'Footer',
        parent=base_styles['Normal'],
        fontSize=8,
        textColor=HexColor('#999999'),
        spaceAfter=0,
        alignment=TA_CENTER,
        fontName='Helvetica-Oblique'
    )
    
    return {
        'header_title': header_title,
        'header_date': header_date,
        'monospace_body': monospace_body,
        'footer': footer
    }


def _escape_html(text: str) -> str:
    """
    Escape HTML special characters for ReportLab.
    
    Args:
        text: Input text
        
    Returns:
        Escaped text safe for ReportLab rendering
    """
    if not text:
        return ""
    
    text = text.replace('&', '&amp;')
    text = text.replace('<', '&lt;')
    text = text.replace('>', '&gt;')
    
    return text
