"""
MOM rendering and edit-application helpers.
"""
from datetime import datetime, timezone

from core.schema import MeetingMOM, ActionItem


def _format_action_cell(value: str, width: int) -> str:
    text = (value or "").strip()
    if len(text) > width:
        text = text[: width - 3] + "..."
    return text.ljust(width)


def format_action_items(action_items: list[ActionItem]) -> list[str]:
    """
    Format action items in a compact table-like style.

    Args:
        action_items: List of typed action items

    Returns:
        List of output lines
    """
    if not action_items:
        return ["  None"]

    action_width = 34
    owner_width = 18
    deadline_width = 24
    status_width = 12

    lines = []
    header = (
        f"  {'#':<3}| "
        f"{_format_action_cell('Action', action_width)} | "
        f"{_format_action_cell('Owner', owner_width)} | "
        f"{_format_action_cell('Deadline', deadline_width)} | "
        f"{_format_action_cell('Status', status_width)}"
    )
    divider = (
        f"  {'-' * 3}+"
        f"-{'-' * action_width}-+-"
        f"{'-' * owner_width}-+-"
        f"{'-' * deadline_width}-+-"
        f"{'-' * status_width}"
    )

    lines.append(header)
    lines.append(divider)

    for index, item in enumerate(action_items, start=1):
        deadline = item.deadline if item.deadline else "No deadline specified"
        owner = item.owner if item.owner else "Unassigned"
        status = item.status if item.status else "Open"
        lines.append(
            f"  {index:<3}| "
            f"{_format_action_cell(item.action, action_width)} | "
            f"{_format_action_cell(owner, owner_width)} | "
            f"{_format_action_cell(deadline, deadline_width)} | "
            f"{_format_action_cell(status, status_width)}"
        )

    return lines


def mom_to_text(mom: MeetingMOM) -> str:
    """
    Render a typed MOM object into corporate MOM text format.

    Args:
        mom: Validated MeetingMOM instance

    Returns:
        Formatted MOM text
    """
    attendees = mom.attendees or []
    parking_lot = mom.parking_lot or []

    lines = [
        "MINUTES OF MEETING",
        "=" * 72,
        f"Title: {mom.title}",
        f"Date: {mom.date}",
        "",
        "Objective:",
        f"  {mom.objective}",
        "",
        "Attendees:",
    ]

    if attendees:
        for attendee in attendees:
            lines.append(f"  - {attendee}")
    else:
        lines.append("  None")

    lines.append("")
    lines.append("Key Decisions:")
    if mom.decisions:
        for index, decision in enumerate(mom.decisions, start=1):
            lines.append(f"  {index}. {decision.text}")
    else:
        lines.append("  None")

    lines.append("")
    lines.append("Action Items:")
    lines.extend(format_action_items(mom.action_items))

    lines.append("")
    lines.append("Parking Lot:")
    if parking_lot:
        for index, item in enumerate(parking_lot, start=1):
            lines.append(f"  {index}. {item}")
    else:
        lines.append("  None")

    lines.append("")
    lines.append("Notes:")
    lines.append(f"  {mom.notes if mom.notes else 'None'}")
    lines.append("")

    audit_time = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines.append(f"Audit: Generated by ClearMeet from structured MOM at {audit_time}")

    return "\n".join(lines)


def apply_user_edits(structured: MeetingMOM, edited_text: str) -> MeetingMOM:
    """
    Apply user edits to MOM for MVP behavior.

    For MVP, structured fields remain unchanged. The caller stores edited_text
    separately and may treat it as export truth.

    Args:
        structured: Validated MeetingMOM instance
        edited_text: User-edited full-text MOM

    Returns:
        Unchanged structured MeetingMOM
    """
    _ = edited_text
    return structured
